version: 1.0.0
groups:
  default:
    targets:
      clean:
        help: Clean unnecessary temporary files
        run: |
          rm -fr build/
          rm -fr dist/
          rm -fr .eggs/
          find . -name '*.egg-info' -exec rm -fr {} +
          find . -name '*.egg' -exec rm -f {} +
          find . -name '*.pyc' -exec rm -f {} +
          find . -name
          find . -name '__pycache__' -exec rm -fr '*.pyo' -exec rm -f {} +
          find . -name '*~' -exec rm -f {} +{} +
          rm -f .coverage
          rm -fr htmlcov/
          rm -fr .pytest_cache

  docs:
    env-file: .env
    targets:
      build:
        help: Build documentation
        run: |
          mkdocs build --config-file docs/mkdocs.yaml

      preview:
        help: Preview documentation page locally
        run: mkdocs serve --watch docs --config-file docs/mkdocs.yaml

  release:
    env-file: .env
    vars:
      app: |
        npx --yes \
        -p semantic-release \
        -p "@semantic-release/commit-analyzer" \
        -p "@semantic-release/release-notes-generator" \
        -p "@semantic-release/changelog" \
        -p "@semantic-release/exec" \
        -p "@semantic-release/github" \
        -p "@semantic-release/git" \
        -p "@google/semantic-release-replace-plugin" \
        semantic-release

    targets:
      ci:
        help: Run semantic release on CI
        run: {{ app }} '--ci'

      dry:
        help: Run semantic release in dry-run mode
        run: {{ app }} '--dry-run'

  tests:
    targets:
      lint:
        help: Run linter tools
        run: pre-commit run --all-files --verbose

      unittest:
        help: Run tests
        run: pytest -s -vv tests

      makim-file-simple:
        help: Test makim using a simple makimfile
        args:
          verbose-mode:
            help: Run the all the tests in verbose mode
            type: bool
            action: store_true
        env:
          MAKIM_FILE: ./tests/.makim-simple.yaml
          VERBOSE_FLAG: '{{ "--verbose" if args.verbose_mode else "" }}'
        shell: bash
        run: |
          makim --makim-file $MAKIM_FILE --help
          makim --makim-file $MAKIM_FILE --version
          makim --makim-file $MAKIM_FILE clean $VERBOSE_FLAG
          makim --makim-file $MAKIM_FILE default.clean $VERBOSE_FLAG
          makim --makim-file $MAKIM_FILE build $VERBOSE_FLAG
          makim --makim-file $MAKIM_FILE default.build $VERBOSE_FLAG
          makim --makim-file $MAKIM_FILE build --clean $VERBOSE_FLAG

      makim-file-complex:
        help: Test makim using a complex makimfile
        env:
          MAKIM_FILE: ./tests/.makim-complex.yaml
          VERBOSE_FLAG: '{{ "--verbose" if args.verbose_mode else "" }}'
        args:
          verbose-mode:
            help: Run the all the tests in verbose mode
            type: bool
            action: store_true
        shell: bash
        run: |
          makim --makim-file $MAKIM_FILE --help
          makim --makim-file $MAKIM_FILE --version
          makim --makim-file $MAKIM_FILE default.lint --verbose
          makim --makim-file $MAKIM_FILE build.clean-gcda --verbose
          makim --makim-file $MAKIM_FILE build.clean --verbose
          makim --makim-file $MAKIM_FILE build.install --verbose
          makim --makim-file $MAKIM_FILE build.release --verbose
          makim --makim-file $MAKIM_FILE build.release --build-type debug --verbose
          makim --makim-file $MAKIM_FILE build.release --extras '-D' --verbose
          makim --makim-file $MAKIM_FILE build.release --clean --verbose
          makim --makim-file $MAKIM_FILE build.dev --verbose
          makim --makim-file $MAKIM_FILE env.create-file --verbose
          makim --makim-file $MAKIM_FILE conda.build --verbose
          makim --makim-file $MAKIM_FILE release.ci --verbose
          makim --makim-file $MAKIM_FILE release.dry --verbose
          makim --makim-file $MAKIM_FILE docs.api --verbose
          makim --makim-file $MAKIM_FILE docs.build --verbose
          makim --makim-file $MAKIM_FILE docs.clean --verbose
          makim --makim-file $MAKIM_FILE docs.preview --verbose
          makim --makim-file $MAKIM_FILE tests.sanitizer --verbose
          makim --makim-file $MAKIM_FILE tests.code-coverage --verbose
          makim --makim-file $MAKIM_FILE tests.gen-object --verbose
          makim --makim-file $MAKIM_FILE tests.gen-ast --verbose
          makim --makim-file $MAKIM_FILE tests.gen-llvm-ir --verbose
          makim --makim-file $MAKIM_FILE tests.examples --verbose
          makim --makim-file $MAKIM_FILE tests.all --verbose
          makim --makim-file $MAKIM_FILE debug.fibonacci --verbose
          makim --makim-file $MAKIM_FILE print.local-env-vars --verbose
          makim --makim-file $MAKIM_FILE print.makim-env-vars --verbose
          makim --makim-file $MAKIM_FILE print.dotenv-var --verbose
          makim --makim-file $MAKIM_FILE print.nested --verbose

      containers:
        help: Test makim with containers-sugar
        env:
          MAKIM_FILE: .makim-complex.yaml
          VERBOSE_FLAG: '{{ "--verbose" if args.verbose_mode else "" }}'
        args:
          verbose-mode:
            help: Run the all the tests in verbose mode
            type: bool
            action: store_true
        shell: bash
        run: |
          cd ./tests/
          makim --makim-file $MAKIM_FILE containers.run --verbose

      makim-file-unittest:
        help: Test makim using a unittest makimfile
        args:
          verbose-mode:
            help: Run the all the tests in verbose mode
            type: bool
            action: store_true
        env:
          MAKIM_FILE: ./tests/.makim-unittest.yaml
          VERBOSE_FLAG: '{{ "--verbose" if args.verbose_mode else "" }}'
        shell: bash
        run: |
          makim --makim-file $MAKIM_FILE --help
          makim --makim-file $MAKIM_FILE --version
          makim --makim-file $MAKIM_FILE tests.test-1 $VERBOSE_FLAG
          makim --makim-file $MAKIM_FILE tests.test-2 --all $VERBOSE_FLAG
          makim --makim-file $MAKIM_FILE tests.test-3-a $VERBOSE_FLAG
          makim --makim-file $MAKIM_FILE tests.test-3-b $VERBOSE_FLAG
          makim --makim-file $MAKIM_FILE tests.test-4 $VERBOSE_FLAG
          makim --makim-file $MAKIM_FILE tests.test-4 --trigger-dep $VERBOSE_FLAG
          makim --makim-file $MAKIM_FILE tests.test-5 $VERBOSE_FLAG
          makim --makim-file $MAKIM_FILE tests.test-6 $VERBOSE_FLAG
